import { SupporterType } from "../Supporter/types";

export const supporters: SupporterType[] = [
  {
    firstName: "Alenka",
    lastName: "Doulain",
    city: "Montpellier",
    occupation:
      "Conseillère à la Métropole et Conseillère Municipale de Montpellier",
    message: "",
  },
  {
    firstName: "René",
    lastName: "Revol",
    city: "Grabels",
    occupation: "Maire de Grabels",
    message: "",
  },
  {
    firstName: "Robert",
    lastName: "Trinquier",
    city: "Jacou",
    occupation:
      "Maire adjoint de jacou de 1989-2016 · Membre de la direction départementale du PCF",
    message: "",
  },
  {
    firstName: "Laura",
    lastName: "Falco",
    city: "Montpellier",
    occupation: "Membre du collectif des Essentielles du lien & du soin",
    message: "",
  },
  {
    firstName: "Denis",
    lastName: "Pèbre",
    city: "Lunel",
    occupation: "Auxiliaire de vie sociale",
    message:
      "La perspective d'obtenir une majorité à l'assemblée nationale sous la bannière NUPES est le plus grand et le plus beau message d'espoir que l'on peut offrir aux citoyens de ce pays ! Enfin un projet qui se propose d'améliorer le quotidien de 90% de la population !",
  },
  {
    firstName: "Laurence",
    lastName: "Moroy",
    city: "Saturargues",
    occupation: "Retraitée",
    message:
      "Sur le programme d'union je suis convaincue de l'espoir à gauche. L'élection d'une opposition réelle à l'assemblée Nationale est fondamentale pour l'avenir en France.",
  },
  {
    firstName: "Lise",
    lastName: "Florès",
    city: "Lunel",
    occupation: "Agent territorial",
    message: "",
  },
  {
    firstName: "Jean-Michel",
    lastName: "Hélary",
    city: "Montferrier-sur-Lez",
    occupation: "Retraité Enseignant-Chercheur",
    message:
      "Julia Mignacca incarne sur la 3ème circonscription de l'Hérault la seule alternative écologique et sociale à l'entreprise de démolition systématique d'Emmanuel Macron. Elle représente aussi un bel exemple de renouveau des élues et élus de notre département. Bien que n'étant membre d'aucun parti, je soutiens fortement sa candidature, porteuse d'un grand espoir.",
  },
  {
    firstName: "Frederic",
    lastName: "Stein",
    city: "Sussargues",
    occupation: "Directeur de théâtre",
    message:
      "Votre engagement personnel dans l'écologie, la fraternité qui se dégage de vos propos dans une campagne sérieuse, dynamique et joyeuse, me font croire que vous serez la meilleure représentante de notre territoire et de sa diversité à l'assemblée nationale.",
  },
  {
    firstName: "Bruno",
    lastName: "Chichignoud",
    city: "Prades-le-Lez",
    occupation:
      "Directeur Maison des Adolescents · Candidat EELV aux Départementales 2021",
    message: "une formidable future députée ",
  },
  {
    firstName: "Frédéric",
    lastName: "Fesquet",
    city: "Prades-le-Lez",
    occupation: "Élu, adjoint à la Mairie de Prades-le-Les",
    message: "",
  },
  {
    firstName: "Stéphanie",
    lastName: "Beuf",
    city: "Montpellier",
    occupation: "Illustratrice et Graphiste en e-learning",
    message: "",
  },
  {
    firstName: "Arthur",
    lastName: "Lenoir",
    city: "Montpellier",
    occupation: "Ingénieur · Militant écologiste",
    message: "",
  },
  {
    firstName: "Florence",
    lastName: "Maurin",
    city: "Saint-Brès",
    occupation: "",
    message:
      "Je soutiens la candidate Julia pour une action politique économique environnementale et sociale",
  },
  {
    firstName: "Dominique",
    lastName: "Faure-Billet",
    city: "Saturargues",
    occupation: "Ingénieur informatique",
    message: "Enfin une union de la gauche avec un vrai programme de gauche.",
  },
  {
    firstName: "Véronique",
    lastName: "Adell",
    city: "Saturargues",
    occupation: "Agent technique",
    message: "",
  },
  {
    firstName: "Gérald",
    lastName: "Perrier",
    city: "Saturargues",
    occupation: "Retraité",
    message: "",
  },
  {
    firstName: "Henri",
    lastName: "Marchesi",
    city: "Castelnau-le-Lez",
    occupation: "Retraité · Communiste",
    message:
      "L'élection de Julia permettra de faire reculer la politique libérale du gouvernement Macron qui ne fait rien pour réduire la crise climatique et détruit tous les acquis sociaux.",
  },
  {
    firstName: "Margaux",
    lastName: "Cosne",
    city: "Montpellier",
    occupation: "Médecin généraliste",
    message: "",
  },
  {
    firstName: "Paul",
    lastName: "Muraille",
    city: "Saussines",
    occupation: "Maître de conférence",
    message: "",
  },
  {
    firstName: "Corentin",
    lastName: "Crochemore",
    city: "Castelnau-le-Lez",
    occupation: "Étudiant histoire-géographie (enseignement)",
    message:
      "Militant et citoyen actif dans le monde associatif depuis des années (distribution alimentaire, éducation populaire, soutien scolaire), je fais pleinement confiance à Julia Mignacca pour défendre l’intérêt des travailleurs et des travailleuses et de notre bien commun à tous et toutes, la Terre et son écosystème.",
  },
  {
    firstName: "Dorian",
    lastName: "Paquet",
    city: "Jacou",
    occupation: "Étudiant en lettres",
    message: "",
  },
  {
    firstName: "Benjamin",
    lastName: "Mouret",
    city: "Beaulieu",
    occupation: "Directeur Technique Artistique - jeu vidéo",
    message:
      "Je soutiens Julia Mignacca et la NUPES pour un avenir plus respectueux de l'intérêt collectif et de l'environnement, pour un partage des richesses plus juste, et un avenir en commun.",
  },
  {
    firstName: "Hugues",
    lastName: "Ferrand",
    city: "Castelnau-le-Lez",
    occupation: "Conseiller municipal",
    message:
      "Je soutiens la candidature de Julia Mignaca pour porter les valeurs d'écologie, de politique sociale et de solidarité dont nous avons besoin. Elle sera compétente, efficace et d'une probité sans faille pour agir au plus haut niveau et représenter l'espoir d'un meilleur avenir pour les générations futures.",
  },
  {
    firstName: "Valérie",
    lastName: "Pagan",
    city: "Castries",
    occupation: "Enseignante",
    message:
      "Soutien total! ✌Force à vous!! Pour la justice sociale et écologique! Pour le respect des services publics!",
  },
  {
    firstName: "Joëlle",
    lastName: "Arneodo",
    city: "Castelnau-le-Lez",
    occupation: "Retraitée Assistante de service social",
    message:
      "Pour le maintien de services publics de qualité, notamment hôpitaux et services de soins, enseignement scolaire et universitaire, recherche, justice, etc… Pour le soutien à une agriculture plus saine, à une meilleure préservation de la nature. Pour une réflexion de fond vers la relocalisation de l'économie. Pour l'engagement dans une société plus solidaire, plus équitable ...etc...",
  },
  {
    firstName: "Myriam",
    lastName: "Bui-Xuan",
    city: "Clapiers",
    occupation: "Adjointe au maire déléguée à l’action sociale ",
    message:
      "Julia Mignacca à l’Assemblée, garantie d’une vraie rupture avec le néolibéralisme, rupture nécessaire pour conjuguer justice climatique et justice sociale.",
  },
  {
    firstName: "Maxime",
    lastName: "Leguillon",
    city: "Montpellier",
    occupation: "Dirigeant associatif",
    message: "",
  },
  {
    firstName: "Françoise",
    lastName: "Argenson",
    city: "Catelanu-le-Lez",
    occupation:
      "Cadre opérationnel Pôle emploi · Présidente d'une association de parents d'élèves",
    message: "",
  },
  {
    firstName: "Michel",
    lastName: "Minenna",
    city: "Castelnau-le-Lez",
    occupation: "Retraité",
    message: "Jusqu'à la victoire",
  },
  {
    firstName: "Christian",
    lastName: "Bouchet",
    city: "Castelnau-le-Lez",
    occupation:
      "Président association des riverains Sablas Sablassou à Castelnau Le Lez",
    message: "",
  },
  {
    firstName: "Brigitte",
    lastName: "Mora",
    city: "Castelnau-Le-Lez",
    occupation: "Retraitée bibliothécaire",
    message:
      "Bibliothécaire à la retraite, habitant Castelnau-Le-Lez depuis 30 ans, guidée par des valeurs humanistes, je suis engagée depuis toujours dans ma vie professionnelle et dans ma vie associative pour plus de justice sociale, pour le droit de chacune et de chacun à vivre dans la dignité, pour le bien commun. Julia Mignacca représente des partis et des forces de progrès, elle porte des valeurs fortes qui sont les miennes. Je suis convaincue qu'elle les défendra avec énergie, conviction et sera à l'écoute des habitants de la circonscription.",
  },
  {
    firstName: "Samuel",
    lastName: "Clot",
    city: "Beaulieu",
    occupation: "",
    message: "",
  },
  {
    firstName: "Anne",
    lastName: "Sarmeo",
    city: "Cazilhac",
    occupation: "Médecin retraité active",
    message: "",
  },
  {
    firstName: "Donovan",
    lastName: "Boisset",
    city: "Castelnau-le-Lez",
    occupation: "Consultant",
    message: "Allez les verts !",
  },
  {
    firstName: "Fanny",
    lastName: "Segui",
    city: "Montpellier",
    occupation: "Compositrice et chanteuse",
    message: "",
  },
  {
    firstName: "Laurent",
    lastName: "Baïbarac",
    city: "Castries",
    occupation: "Retraité · Militant syndical",
    message:
      "Pour un 3eme tour victorieux, et un 4eme tour social qui nous permettra de mettre en œuvre le programme de la NUPES, je vote et j'appelle à voter pour Julia.",
  },
  {
    firstName: "Mina",
    lastName: "Brisset",
    city: "Montferrier-sur-Lez",
    occupation: "Jeunes Ecologistes",
    message:
      "Julia Mignacca est la première candidate à une élection qui me donne autant d'espoir. J'ai 18 ans et je suis heureuse, vraiment heureuse, de pouvoir voter par conviction et m'engager, et espérer faire gagner la gauche écologiste !",
  },
  {
    firstName: "Rémi",
    lastName: "Bouix",
    city: "Castries",
    occupation: "Conseiller Municipal de Castries",
    message:
      "Julia incarne l'union historique de la gauche et des écologistes, qui est porteuse d'espoirs de victoire !",
  },
  {
    firstName: "Philippe",
    lastName: "Compan",
    city: "Saussines",
    occupation: "Retraité",
    message: "Un autre monde est possible.",
  },
  {
    firstName: "Eric",
    lastName: "Gasiglia",
    city: "Entre-vignes",
    occupation: "Élu Mairie Entre-vignes",
    message:
      "Nous partageons de nombreuses valeurs communes et nous œuvrons chacun à notre niveau pour les transformer en réalité quotidienne !",
  },
  {
    firstName: "Nicolas",
    lastName: "Desagher",
    city: "Beaulieu",
    occupation: "Steward",
    message: "",
  },
  {
    firstName: "Bruno",
    lastName: "Pignard",
    city: "Teyran",
    occupation: "Cadre informatique",
    message:
      "Je soutiens Julia qui porte les valeurs écologiques et de justice sociale dans lesquelles je crois.  ",
  },
  {
    firstName: "Audrey",
    lastName: "Bramy",
    city: "Montpellier",
    occupation: "Co-gérante d'une SCOP",
    message: "",
  },
  {
    firstName: "Clothilde",
    lastName: "Ollier",
    city: "Montpellier",
    occupation: "Conseillère municipale et métropolitaine",
    message: "",
  },
  {
    firstName: "Stéphan",
    lastName: "Gély",
    city: "Lunel",
    occupation: "Opérateur/ Syndicaliste",
    message:
      "Tout mon soutien pour la candidature de Julia sur la troisième circonscription de l'Hérault qui représente la N.U.P.E.S. Amicalement Stéphan Gély",
  },
  {
    firstName: "Carine",
    lastName: "Barbier",
    city: "Castelnau-Le-Lez",
    occupation: "Conseillère municipale",
    message: "",
  },
  {
    firstName: "Jean-Laurent",
    lastName: "Noé",
    city: "Saint-Christol",
    occupation: "Ingénieur",
    message: "",
  },
  {
    firstName: "Jean-Philippe",
    lastName: "Aynie",
    city: "Montpellier",
    occupation: "",
    message: "",
  },
  {
    firstName: "Mathilde",
    lastName: "Borne",
    city: "Castelnau-le-Lez",
    occupation: "Conseillère Municipale et Metropolitaine Ville de Castelnau-le-Lez",
    message: "",
  },
  {
    firstName: "Nadine ",
    lastName: "Canet",
    city: "Castries",
    occupation: "Retraitée citoyenne militante",
    message: "Un monde meilleur est possible avec Julia et la Nupes ! Bravo pour ton engagement et ton enthousiasme !",
  },
  {
    firstName: "Priscillia",
    lastName: "Mollet",
    city: "Galargues",
    occupation: "Vendeuse",
    message: "Je soutiens Julia, mon vote ne sera pas présent car ma santé ne me le permet pas. Je tiens donc à écrire mon soutien ici même. Notre pays va mal et avec Macron ça n'est pas prêt d'aller mieux mais de pire en pire comme ça l'est déjà depuis trop longtemps... Je suis de tout cœur avec vous ! Hérault 34 votez Mignacca !!!!! ",
  },
  {
    firstName: "Remi",
    lastName: "Serveau",
    city: "Lunel",
    occupation: "",
    message: "Julia représente l'avenir et je sais qu'elle mènera une politique exemplaire, transparente et citoyenne. Elle a tout mon soutien.",
  },
  {
    firstName: "Denis",
    lastName: "Orcel",
    city: "Montpellier",
    occupation: "Adjoint technique Université de Montpellier",
    message: "Parce que le changement ne se fera pas sans rupture. Face aux crises sociales, environnementales, économiques il n'est plus question de changer de logiciel mais de système d'exploitation. Je crois dans ce projet collectif mais je resterai vigilent quant à sa mise en œuvre. Votre victoire, notre victoire me laisserait penser que cet autre monde possible est juste là, à portée de main. Tout mon soutien. Force et courage.",
  },
  {
    firstName: "Gregory",
    lastName: "Castellani",
    city: "Teyran",
    occupation: "Ingénieur en électronique",
    message: "",
  },
  {
    firstName: "Valérie",
    lastName: "Morin",
    city: "Castelnau-le-Lez",
    occupation: "Notaire assistant",
    message: "",
  },
  {
    firstName: "Dominique",
    lastName: "Carré",
    city: "Castelnau-le-Lez",
    occupation: "Retraitée de l'Éducation Nationale",
    message: "Le 12/6 et le 19/6 Je vote pour Julia-députée, et le magnifique programme que nous avons élaboré ensemble.",
  },
  {
    firstName: "Jacques Antoine",
    lastName: "MARTINI",
    city: "Montpellier",
    occupation: "Avocat honoraire · Secrétaire Général d'Université en retraite",
    message: "",
  },
  {
    firstName: "Lucile",
    lastName: "Jouve",
    city: "Montpellier",
    occupation: "Chargée de Mission éducation à l'environnement",
    message: "",
  },
  {
    firstName: "Jeghdagh",
    lastName: "Halima",
    city: "Castelnau-le-Lez",
    occupation: "Reconversion professionnelle",
    message: "Courage on vous soutient !!! Je vais voter pour vous.",
  },
  {
    firstName: "Frederic",
    lastName: "Ortiz",
    city: "Castelnau-le-Lez",
    occupation: "president association MASCS + IC INFORMATIQUE",
    message: "",
  },
  {
    firstName: "Jean-Jacques",
    lastName: "Drevon",
    city: "Castelnau-le-Lez",
    occupation: "Agrophysiologiste (ex INRAE) Directeur Scientifique du DEVA",
    message: "J'apporte mon soutien aux engagement de Julia M pour notre circonscription en particulier dans le champ de mes compétences pour une agriculture écologique et paysanne, et sur les ambitions climatique et les énergies renouvelables.",
  },
  {
    firstName: "Vincent",
    lastName: "Meynier",
    city: "Clapiers",
    occupation: "Conseiller Municipal",
    message: "Je partage totalement la vision de l'écologie de Julia avec qui j'ai travaillé sur des problèmes métropolitains dans le passé. J'apprécie son dynamisme et sa rectitude de pensée. Elle fera une excellente députée. J'apporte tout mon soutien actif a sa campagne! Uni.e.s, nous enverrons la gauche et l'écologie à l'Assemblée pour contrer la politique antisociale et écocide du gouvernement Macron 2.",
  },
  {
    firstName: "Fanny",
    lastName: "Pebre",
    city: "Saint-Bres",
    occupation: "",
    message: "Tous ensemble pour un avenir meilleur ",
  },
  {
    firstName: "Anna",
    lastName: "Midol Monnet",
    city: "Castries",
    occupation: "Boulangère",
    message: "",
  },
  {
    firstName: "Jean-Jacques",
    lastName: "Carrere",
    city: "Vias",
    occupation: "Retraité",
    message: "Parce que le monde est en danger, parce que la santé va mal, l'éducation va mal, tous nos services publics vont mal, parce que le dérèglement climatique impacte l'avenir de notre territoire et sa capacité à nourrir ses habitants, il faut \"renverser la table\", changer nos moyens de production et de consommation, prendre résolument des directives pour préserver notre environnement et protéger les plus fragiles. Julia incarne ce combat qu'il nous faut mener pour rompre ce cycle infernal où on consomme plus que la terre ne produit et où les plus riches sont toujours plus riches et le nombre de pauvres augmentent toujours plus. Julia doit aller à l'Assemblée National où sa jeunesse, sa pugnacité et sa ténacité permettront de relever ce défi majeur de notre Histoire.",
  },
  {
    firstName: "Patrick",
    lastName: "Brechotteau",
    city: "Jacou",
    occupation: "Conseiller municipal JACOU citoyenne écologique et sociale",
    message: "Julia une députée pour porter les revendications écologiques et sociales de la population jacoumarde et de la troisième circonscription de l Hérault à l'Assemblée Nationale.",
  },
  {
    firstName: "Enzo",
    lastName: "Blondeau",
    city: "Montpellier",
    occupation: "Médiateur scientifique",
    message: "Portons la NUPES à l'assemblée nationale pour un réel changement social et environnemental ! Merci Julia pour ce combat que vous menez ! Courage, on peut le faire !",
  },
  {
    firstName: "Dominique",
    lastName: "Nurit",
    city: "Castelnau-Le-Lez",
    occupation: "Psychotherapeute",
    message: "Julia réunit toutes les valeurs et qualités nécessaires à cette fonction et précieuses pour le virage à prendre concernant le social et l’écologie.",
  },
  {
    firstName: "Emmanuel",
    lastName: "Ferrer Minguez",
    city: "Montpellier",
    occupation: "Professeur de SVT · Formateur en botanique",
    message: "Un souffle d'espoir pour stopper la politique du président. Une alternative pour les classes populaire et moyenne, une alternative pour sauver la fonction publique en particulier l'école et l'hôpital. Un vrai espoir pour enfin mener une politique sociale et écologique. Dimanche, Julia MIGNACCA une dame du peuple, doit siéger à l'assemblée. ",
  },
  {
    firstName: "Arnaud",
    lastName: "Clappier",
    city: "Montpellier",
    occupation: "Gérant de cinéma",
    message: "",
  },
  {
    firstName: "Djoe",
    lastName: "Bonev",
    city: "Castelnau-le-Lez",
    occupation: "",
    message: "",
  },
  {
    firstName: "François",
    lastName: "Masselot",
    city: "Clapiers",
    occupation: "Conseiller municipal délégué",
    message: "Pour l'écologie politique, pour la justice sociale, pour une démocratie vivante, pour la réduction des inégalités, pour l'avenir, je vote Julia Mignacca",
  },
  {
    firstName: "Gilles",
    lastName: "Dutau",
    city: "Clapiers",
    occupation: "élu Mairie de Clapiers",
    message: "Pour que Julia puisse porter avec force la parole de l'écologie politique au sein d'une assemblée qui doit rester la boussole de notre République.",
  },
  {
    firstName: "Annie",
    lastName: "Sequier-Blanc",
    city: "Montpellier",
    occupation: "",
    message: "",
  },
  {
    firstName: "Marie",
    lastName: "Germain",
    city: "Castries",
    occupation: "Artisante tapissiere",
    message: "",
  },
  {
    firstName: "Fabrice",
    lastName: "Pages",
    city: "Montpellier",
    occupation: "Attaché Territorial",
    message: "",
  },
  {
    firstName: "Rudolf",
    lastName: "Mizzi",
    city: "Restinclieres",
    occupation: "Producteur audiovisuel",
    message: "",
  },
  {
    firstName: "Anne",
    lastName: "Tricard",
    city: "Montferrier sur Lez",
    occupation: "Bénévole CADA",
    message: "",
  },
];
